# mysql
development:
  adapter: mysql2
  database: library_development
  username: root
  password: enbake
  host: localhost

test:
  adapter: mysql2
  database: library_test
  username: root
  password: enbake
  host: localhost

production:
  adapter: mysql2
  database: library_development
  username: root
  password: enbake
  host: localhost